apiVersion: v1
entries:
  escalation-eda:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-11-10T10:28:08.01255733Z"
    description: 'A Helm chart to install the escalation application(s): * jira-listener
      Knative service * (optional) event-display Knative service * required Knative
      eventing resoures (Trigger, SinkBinding and Broker) '
    digest: 322cd0ed6c637cde3a4e87a499d3125fae83aee8ffeb11e1eabca66f7da03787
    name: escalation-eda
    type: application
    urls:
    - https://dmartinol.github.io/serverless-workflow-examples/charts/latest/escalation-eda-1.0.0.tgz
    version: 1.0.0
generated: "2023-11-10T10:28:08.011816024Z"
